/* <![CDATA[ */
var jetpackCarouselStrings = {
    "widths": [370, 700, 1000, 1200, 1400, 2000],
    "is_logged_in": "",
    "lang": "en",
    "ajaxurl": "https:\/\/design.maker.themepatio.com\/wp-admin\/admin-ajax.php",
    "nonce": "76e6d9cdfd",
    "display_exif": "0",
    "display_geo": "1",
    "single_image_gallery": "1",
    "single_image_gallery_media_file": "",
    "background_color": "black",
    "comment": "Comment",
    "post_comment": "Post Comment",
    "write_comment": "Write a Comment...",
    "loading_comments": "Loading Comments...",
    "download_original": "View full size <span class=\"photo-size\">{0}<span class=\"photo-size-times\">\u00d7<\/span>{1}<\/span>",
    "no_comment_text": "Please be sure to submit some text with your comment.",
    "no_comment_email": "Please provide an email address to comment.",
    "no_comment_author": "Please provide your name to comment.",
    "comment_post_error": "Sorry, but there was an error posting your comment. Please try again later.",
    "comment_approved": "Your comment was approved.",
    "comment_unapproved": "Your comment is in moderation.",
    "camera": "Camera",
    "aperture": "Aperture",
    "shutter_speed": "Shutter Speed",
    "focal_length": "Focal Length",
    "copyright": "Copyright",
    "comment_registration": "0",
    "require_name_email": "1",
    "login_url": "https:\/\/design.maker.themepatio.com\/wp-login.php?redirect_to=https%3A%2F%2Fdesign.maker.themepatio.com%2Fstyle-guide%2F",
    "blog_id": "12",
    "meta_data": ["camera", "aperture", "shutter_speed", "focal_length", "copyright"],
    "local_comments_commenting_as": "<fieldset><label for=\"email\">Email (Required)<\/label> <input type=\"text\" name=\"email\" class=\"jp-carousel-comment-form-field jp-carousel-comment-form-text-field\" id=\"jp-carousel-comment-form-email-field\" \/><\/fieldset><fieldset><label for=\"author\">Name (Required)<\/label> <input type=\"text\" name=\"author\" class=\"jp-carousel-comment-form-field jp-carousel-comment-form-text-field\" id=\"jp-carousel-comment-form-author-field\" \/><\/fieldset><fieldset><label for=\"url\">Website<\/label> <input type=\"text\" name=\"url\" class=\"jp-carousel-comment-form-field jp-carousel-comment-form-text-field\" id=\"jp-carousel-comment-form-url-field\" \/><\/fieldset>"
};
/* ]]> */